# name: deploy-container

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'packages/container/**'

# defaults:
#   run:
#     working-direcory: packages/container

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - run: npm install
#       - run: npm run build

#       - uses: shinyinc/action-aws-cli@v1.2
#       - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/container/latest
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code       # Step name added for clarity
        uses: actions/checkout@v2

      - name: Set working directory # Correctly sets the working directory
        run: cd packages/container

      - name: Install dependencies # Step name added for clarity
        run: npm install

      - name: Build the project    # Step name added for clarity
        run: npm run build

      - name: Sync to S3           # Step name added for clarity
        uses: shinyinc/action-aws-cli@v1.2
        with:
          args: "aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
